### ISSUE TITLE
Consolidate swipeforfuture.com and swipeforfuture-content into a singe repository

### ISSUE THREAD

**Issue by Greenheart** [Muthaias/swipeforfuture-content#17]
Pros:
- Greatly simplified development experience. Just clone a single git repository, install dependencies and you're ready to start developing both the game and official scenarios.
- The scenarios can use shared types directly from the game code base without having to include the game as a git submodule first, which may get out of sync and adds unnecessary complexity.
- Official scenarios can be versioned together with the game, making it easier to test and ensure content works with the game versions.
- Keeping scenarios and the game in the same repository will aid the upcoming refactoring effort to simplify the code base.

Cons:
- Official scenarios will be centralized. This is a acceptable tradeoff IMO since it will greatly simplify the game and scenario development, aiding both new and old contributors. The game itself will still support community scenarios to be loaded from other sources.
- The community contributions will be centralized in one repository. This can be mitigated by creating a GitHub organization and then moving the project there, for shared code ownership.

**Comment by Greenheart** [comment]
# TODO:

- [x] Move code from this project to https://github.com/Greenheart/swipeforfuture.com
- [x] Investigate possibility to compile all game + scenario code using Vite and the same TS config.
- [x] Install dev dependencies used by content scripts
- [x] Add npm scripts for development of scenarios and the game
- [x] Add npm scripts for building scenarios and the game
- [x] Combine scripts and use `concurrently` to provide a smooth DX #23 with a shorthand dev command and build command
- [x] Update type imports to use the same version of `ContentTypes.ts`
- [x] Add deployment scripts
- [x] Deploy new scenarios and game
- [x] Update README and CONTRIBUTING of https://github.com/Greenheart/swipeforfuture.com to explain new development workflow
- [x] Add notice to `swipeforfuture-content` README and explain that future updates to scenarios will be developed in the game repo.
- [x] Update license for the game to GNU GPL v3
- [x] Rename `master` branch of https://github.com/Greenheart/swipeforfuture.com to `main`
